# my global config
global:
  scrape_interval:     15s # By default, scrape targets every 15 seconds.
  evaluation_interval: 15s # By default, scrape targets every 15 seconds.
  # scrape_timeout is set to the global default (10s).

  # Attach these labels to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
      monitor: 'monitoring'

# Load and evaluate rules in this file every 'evaluation_interval' seconds.
rule_files:
  - "alert.rules"

scrape_configs:
  - job_name: 'prometheus'
    dns_sd_configs:
    - names:
      - 'tasks.prometheus'
      type: 'A'
      port: 9090

  - job_name: 'traefik'
    dns_sd_configs:
    - names:
      - 'tasks.traefik'
      type: 'A'
      port: 8080

  - job_name: 'cadvisor'
    dns_sd_configs:
    - names:
      - 'tasks.cadvisor'
      type: 'A'
      port: 8080

  - job_name: 'node-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.node-exporter'
      type: 'A'
      port: 9100

  - job_name: 'docker-exporter'
    dns_sd_configs:
    - names:
      - 'tasks.docker-exporter'
      type: 'A'
      port: 4999

  #- job_name: 'blackbox'
  #  metrics_path: /probe
  #  params:
  #    module: [http_jekyll]
  #  file_sd_configs:
  #    - files: ['/blackbox_targets.yml']
  #  relabel_configs:
  #    - source_labels: [__address__]
  #      regex: (.*)(:80)?
  #      target_label: __param_target
  #    - source_labels: [__param_target]
  #      regex: (.*)
  #      target_label: instance
  #      replacement: ${1}
  #    - source_labels: []
  #      regex: .*
  #      target_label: __address__
  #      replacement: blackbox-exporter:9115

  - job_name: 'blackbox-jekyll'
    metrics_path: /probe
    params:
      module: [http_2xx] 
    static_configs:
      - targets:
        - http://jekyll:4000
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  - job_name: 'blackbox-domaintest'
    metrics_path: /probe
    params:
      module: [http_domaintest]
    static_configs:
      - targets:
        - https://domain.test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter. 

  - job_name: 'blackbox-basicauth'
    metrics_path: /probe
    params:
      module: [http_basicauth]
    static_configs:
      - targets:
        - https://test1.domain.test
        - https://test2.domain.test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter. 

  - job_name: 'blackbox-basicauth-grafana'
    metrics_path: /probe
    params:
      module: [http_basicauth_grafana]
    static_configs:
      - targets:
        - https://grafana.domain.test
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # Blackbox exporter. 
